<?php

namespace App\Http\Controllers;

use App\Models\Link;
use Illuminate\Support\Facades\Auth;

use Illuminate\Http\Request;
use App\Models\User;
use GuzzleHttp\Psr7\Query;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

    public function login(Request $request)
    {    

        $user = User::whereHas('phone',fn($query)=>$query->where('number',$request->phone))->get();
        dd($user->createToken('tokens'));
        return $user->toArray() +
        ['token' => $user->createToken('tokens')->plainTextToken]; // TODO: Change the autogenerated stub

    }

    
}
