<?php

namespace App\Http\Controllers;

use App\Models\Link;
use Illuminate\Support\Facades\Auth;

use Illuminate\Http\Request;
use App\Models\User;
use GuzzleHttp\Psr7\Query;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Facades\Response;


class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

    public function login(Request $request)
    {    

        $user = User::whereHas('phone',fn($query)=>$query->where('number',$request->phone))->get();
        dd($user->createToken('tokens'));
        return $user->toArray() +
        ['token' => $user->createToken('tokens')->plainTextToken]; // TODO: Change the autogenerated stub

    }

    //---------secces----------error---------------------------------
    public function success(
        mixed $data,
        int $status = 200,
        bool $success = true,
        string $message = "success",
    ): JsonResponse
    {
        return Response::json([
            "status"  => $status,
            "success" => $success,
            "message" => $message,
            "result"  => $data,
        ], $status);
    }

    public function error(
        mixed $data,
        int $status = 400,
        bool $success = false,
        string $message = "failed",
    ): JsonResponse
    {
        return Response::json([
            "status"  => $status,
            "success" => $success,
            "message" => $message,
            ...$data,
        ], $status);
    }
    //---------secces----------error---------------------------------


}
